# Generated by Django 4.0.5 on 2022-08-11 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist_chanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof_photo', models.ImageField(null=True, upload_to='profilePictures')),
                ('pictures', models.ImageField(null=True, upload_to='pictures')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricture', models.ImageField(blank=True, null=True, upload_to='Event_picture')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('videos', models.FileField(blank=True, null=True, upload_to='event_videos')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('artist_Relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel', to='Artist_app.artist_chanel')),
            ],
        ),
        migrations.CreateModel(
            name='Event_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('comment_image', models.ImageField(blank=True, null=True, upload_to='commentimage')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventComment', to='Artist_app.event')),
            ],
        ),
    ]
