# Generated by Django 4.0.5 on 2022-07-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artist_app', '0003_rename_comments_comment_rename_events_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_image',
            field=models.ImageField(null=True, upload_to='comment image'),
        ),
    ]
