# Generated by Django 4.0.5 on 2022-07-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artist_app', '0005_alter_comment_comment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='pricture',
            field=models.ImageField(blank=True, null=True, upload_to='Event_picture'),
        ),
        migrations.AlterField(
            model_name='event',
            name='videos',
            field=models.FileField(blank=True, null=True, upload_to='event_videos'),
        ),
    ]
