# Generated by Django 4.0.6 on 2022-08-11 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
