# Generated by Django 4.0.6 on 2022-08-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_alter_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Username',
        ),
        migrations.AddField(
            model_name='user',
            name='User_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
