# Generated by Django 4.0.6 on 2022-08-14 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_remove_user_username_user_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
