# Generated by Django 4.0.5 on 2022-07-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_alter_comments_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment_image',
            field=models.ImageField(null=True, upload_to='comment_image'),
        ),
    ]
