# Generated by Django 4.0.5 on 2022-07-28 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Artist_app', '0002_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comments',
            new_name='comment',
        ),
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
